AudioKit/AudioKitSynthOne

AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp, AudioKitSynthOne/TouchPad/UI Components/AKVerticalPad.swift, Podfile.lock
*add clamped insets to verticalslider for full range of pitchbbend parameter
*do not smooth pitchbend in dsp
=> PitchBend fix

AudioKitSynthOne/Tunings/Base.lproj/Tunings.storyboard, AudioKitSynthOne/Tunings/Model/Tunings+DefaultTunings.swift, AudioKitSynthOne/Tunings/Model/Tunings.swift, AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanel+UITableViewDataSource.swift, AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanel+UITableViewDelegate.swift, AudioKitSynthOne/Tunings/UI Components/TuningCell.swift
Fixed tuning storyboard.
Tested upgrade paths, new bank loading/saving.
New bank "Hexany Triads" with proportional and subcontrary triads of hexanies.  
Each hexany has 4 or 5 proportional triads, and 4 or 5 subcontrary triads.
The tetrany major and minor embedded in these hexanies are also part of the set.
=> Curating hexany triads, storyboard polishing, tuning upgrade paths

AudioKitSynthOne.xcodeproj/project.pbxproj, AudioKitSynthOne/Tunings/Model/Tunings+DefaultTunings.swift, AudioKitSynthOne/Tunings/Model/Tunings+UpgradePaths.swift, AudioKitSynthOne/Tunings/Model/Tunings.swift
also made Tunings file smaller by adding extension Tunings+UpgradePath
=> fixed hexany tuning sorting order issue

AudioKitSynthOne/Controls/Knobs/Knob.swift, AudioKitSynthOne/Controls/Stepper/Stepper.swift, AudioKitSynthOne/Generators/UI Components/MorphSelector.swift
This should restore the accessibility functionality on Knobs and Sliders that Git decided it would erase.
=> Restoring Accessibility Code that got erased.

AudioKitSynthOne/Header/Base.lproj/Header.storyboard
As per Louis and Zach's suggestion, adding a VO hint to let VO users know of the Preset Menu.
=> Added VoiceOver hint indicating presence of the Preset Menu.

AudioKitSynthOne.xcodeproj/project.pbxproj, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+didChanges.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+process.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+reset.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp, AudioKitSynthOne/DSP/Kernel/S1DSPKernel.mm, AudioKitSynthOne/DSP/Sequencer/S1ArpModes.hpp, AudioKitSynthOne/DSP/Sequencer/S1Arpeggiator.hpp, AudioKitSynthOne/DSP/Sequencer/S1SeqNoteNumber.hpp, AudioKitSynthOne/DSP/Sequencer/S1Sequencer.hpp, AudioKitSynthOne/DSP/Sequencer/S1Sequencer.mm
ping @analogcode @marcussatellite 
This is my first iteration of the Sequencer Refactor.
In the first commit I'm extracting the sequencer code from the Kernel into a separate class.
The second commit cleans up and extracts the Arpegiator code into separate static functions.
I also consolidate the Down and DownMinusTail ones into one function.
Tested on my end, but I'd feel way more comfortable if you all would give this a spin too before merging :)
=> Refactor Sequencer

AudioKitSynthOne/DSP/Sequencer/S1Sequencer.hpp, AudioKitSynthOne/DSP/Sequencer/S1Sequencer.mm, AudioKitSynthOne/Sequencer/SequencerPanelController.swift
Improve the Step Counter by calculating the steps directly
instead of increasing.
Move Step Counter to atomic, since we access it from two threads.
Assert if atomicity is given at compile-time.
ping @aure @marcussatellite
=> Improve Step Counter

AudioKitSynthOne/DSP/Audio Unit/S1AudioUnit.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+didChanges.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+getSetDependentParameters.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+getSetSynthParameters.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+parameters.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+process.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+startStopNotes.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel+toggleKeys.mm, AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp, AudioKitSynthOne/DSP/Kernel/S1DSPKernel.mm, AudioKitSynthOne/DSP/Note State/S1NoteState.mm, AudioKitSynthOne/DSP/Sequencer/S1Sequencer.mm
Hey,
few improvements:
a) Use move-semantics for sequencer notes (saves a cpu cycle or two cause we don't copy anymore)
b) (this one might be a bit controversial): rename `p` to `parameters`. This might be more readable and help with understanding the code-base for people new to this.
Let me know what you think.
=> Small Improvements

.travis.yml
Update Travis CI to use Xcode 10 and the pod configuration to always update all pods.
FYI @aure @marcussatellite @analogcode
=> Update Xcode image to 10.1

AudioKitSynthOne/Effects/UI Components/LFOToggle.swift
Fix so Accessibility actually turns off and On the LFOs
=> Fix so Accessibility actually activates and deactivates the LFO

AudioKitSynthOne/DSP/Sequencer/S1Arpeggiator.hpp, AudioKitSynthOne/MIDI/MIDISettingsViewController.swift
Fix some compile errors with xcode 10.2.
=> Fix some XCode 10.2 errors

AudioKitSynthOne/DSP/Kernel/S1DSPKernel+toggleKeys.mm, AudioKitSynthOne/DSP/Note State/S1NoteState.mm
=> testing retrigger for poly for seq/arp

AudioKitSynthOne/AppDelegate.swift
For some reason this turned white. Reverting back to blue.
Closes https://github.com/AudioKit/AudioKitSynthOne/issues/102
=> Revert Done Button back to Blue

README.md
=> Typo fixed on paragraph 17

AudioKitSynthOne/Header/HeaderViewContoller.swift, AudioKitSynthOne/Presets/PresetDataManager.swift, AudioKitSynthOne/Tunings/Model/String+Drawing.swift, AudioKitSynthOne/Tunings/Model/Tuning.swift, AudioKitSynthOne/Tunings/Model/Tunings+DefaultTunings.swift, AudioKitSynthOne/Tunings/Model/Tunings+Drawing.swift, AudioKitSynthOne/Tunings/Model/Tunings+Harmonic.swift, AudioKitSynthOne/Tunings/Model/Tunings+Math.swift, AudioKitSynthOne/Tunings/Model/Tunings+TuneUp.swift, AudioKitSynthOne/Tunings/Model/Tunings+UpgradePaths.swift, AudioKitSynthOne/Tunings/Model/Tunings.swift, AudioKitSynthOne/Tunings/TuneUpPopUp.swift, AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanel+TuneUpDelegate.swift, AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanel+UITableViewDataSource.swift, AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanel+UITableViewDelegate.swift, AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanelController.swift, AudioKitSynthOne/Tunings/TuningsPanelController/TuningsViewController.swift, AudioKitSynthOne/Tunings/UI Components/TuningCell.swift, AudioKitSynthOne/Tunings/UI Components/TuningsPitchWheelOverlayView.swift, AudioKitSynthOne/Tunings/UI Components/TuningsPitchWheelView.swift
Fixed MasterTuning Knob
Display MasterTuning in Header Panel
=> Fixed Master Tuning Knob

AudioKitSynthOne/Base.lproj/Main.storyboard, AudioKitSynthOne/Generators/Base.lproj/Generators.storyboard, AudioKitSynthOne/Generators/GeneratorsPanelController.swift, AudioKitSynthOne/MIDI/MIDIRecordButton.swift
Fixed VoiceOver not seeing record button.
Added some Accessibility Hints too for usage.
=> Fixed VoiceOver not seeing record button.

AudioKitSynthOne/DSP/AudioRecorder.swift, AudioKitSynthOne/DSP/Conductor.swift, AudioKitSynthOne/Developer/Base.lproj/Base.lproj/Dev.storyboard, AudioKitSynthOne/Developer/DevViewController.swift, AudioKitSynthOne/Developer/Manager+DevView.swift, AudioKitSynthOne/Developer/README.md, AudioKitSynthOne/Header/HeaderViewContoller.swift, AudioKitSynthOne/Settings/AppSettings.swift, AudioKitSynthOne/Settings/Manager+AppSettings.swift, AudioKitSynthOne/Tunings/Model/Tunings.swift
Secret HAQ panel toggle to customize recording file base name:
When OFF (default): the record button will create WAV files with the file basename in the format "yyyyMMdd_HHmmss".  
When TRUE: the record button will create filenames in the format: "<tuning name>_<tempo>_yyyyMMdd_HHmmss"
=> Record file basename

AudioKitSynthOne/DSP/AudioRecorder.swift, AudioKitSynthOne/Manager/Manager.swift, AudioKitSynthOne/Settings/Manager+AppSettings.swift
* bug fix for users who opt in to custom record filename option via dev panel.
* default users who don't use dev panel toggle are unaffected (majority of users)
* users who do opt in to custom record filename were unable to switch between default and custom file name.
=> fixed bug in dev panel record file basename

AudioKitSynthOne/Presets/PresetEditorViewController.swift
=> fixed text field when saving presets

AudioKitSynthOne/AppDelegate.swift, AudioKitSynthOne/Base.lproj/Main.storyboard, AudioKitSynthOne/Controls/Buttons/ToggleSwitch.swift, AudioKitSynthOne/DSP/S1Control.swift, AudioKitSynthOne/DSP/TAAE/AEMessageQueue.m, AudioKitSynthOne/Developer/Base.lproj/Base.lproj/Dev.storyboard, AudioKitSynthOne/MIDI/MIDISettingsViewController.swift, AudioKitSynthOne/MIDI/Manager+MIDIListener.swift, AudioKitSynthOne/MIDI/Manager+MIDISettingsPopOverDelegate.swift, AudioKitSynthOne/Navigation/Manager+Navigation.swift, AudioKitSynthOne/Settings/AppSettings.swift
Added knob to MIDISettingsViewController to create a curve for incoming midi velocity
Tested with ROLI Seaboard
Tested iPad and iPhone
=> MIDI Velocity Sensitivity

AudioKitSynthOne/DSP/Sequencer/S1Arpeggiator.hpp
arp: play keys in order pressed for both up, down, and up+down modes
=> arp: play keys in order pressed for both up, down, and up+down modes

AudioKitSynthOne/Controls/Buttons/ToggleButton.swift, AudioKitSynthOne/Controls/Buttons/ToggleSwitch.swift, AudioKitSynthOne/Controls/Knobs/Knob.swift, AudioKitSynthOne/Controls/Stepper/Stepper.swift, AudioKitSynthOne/DSP/Note State/S1NoteState.hpp, AudioKitSynthOne/DSP/Note State/S1NoteState.mm, AudioKitSynthOne/Effects/EffectsPanelController.swift, AudioKitSynthOne/Effects/UI Components/LFOToggle.swift, AudioKitSynthOne/Effects/UI Components/LFOWavePicker.swift, AudioKitSynthOne/Envelopes/EnvelopesPanelController.swift, AudioKitSynthOne/Generators/GeneratorsPanelController.swift, AudioKitSynthOne/Generators/UI Components/FilterTypeButton.swift, AudioKitSynthOne/Generators/UI Components/MorphSelector.swift, AudioKitSynthOne/Header/HeaderNavButton.swift, AudioKitSynthOne/Keyboard/UI Components/KeyboardView+Touches.swift, AudioKitSynthOne/Manager/Manager+callbacks.swift, AudioKitSynthOne/Navigation/NavButton.swift, AudioKitSynthOne/Sequencer/SequencerPanelController.swift, AudioKitSynthOne/Sequencer/UI Components/ArpButton.swift, AudioKitSynthOne/Sequencer/UI Components/ArpDirectionButton.swift, AudioKitSynthOne/Sequencer/UI Components/RateKnob.swift, AudioKitSynthOne/Sequencer/UI Components/SliderTransposeButton.swift, AudioKitSynthOne/Sequencer/UI Components/TempoStepper.swift, AudioKitSynthOne/TouchPad/TouchPadPanelController.swift, AudioKitSynthOne/TouchPad/UI Components/AKTouchPadView.swift, AudioKitSynthOne/TouchPad/UI Components/AKVerticalPad.swift
removed unnecessary code from touchesEnded throughout entire app.
whitespace.
higher order swift.
=> Touches ended

AudioKitSynthOne/Controls/Knobs/Knob.swift
Knobs should once again Inc and Dec values on swipe.
=> Restoring Accessibility Inc Dec functionality on Knobs

AudioKitSynthOne/Manager/Manager+callbacks.swift, AudioKitSynthOne/Manager/Manager.swift
transpose was not being stored in activePreset and was being clobbered when updateUI was called
=> Transpose view did load update bug

AudioKitSynthOne/Header/HeaderViewContoller.swift, AudioKitSynthOne/Presets/Manager+PresetsDelegate.swift, AudioKitSynthOne/Presets/PresetsViewController/Presets+LoadSaveManipulate.swift, AudioKitSynthOne/Presets/PresetsViewController/Presets+UITableViewDataSource.swift, AudioKitSynthOne/Presets/PresetsViewController/PresetsViewController.swift, AudioKitSynthOne/Presets/SearchViewController.swift
randomize presets within the currently selected bank.
=> Random preset in bank

AudioKitSynthOne/DSP/Conductor.swift, AudioKitSynthOne/Header/HeaderViewContoller.swift
added arp params to header label display
=> Header label
