AudioKitSynthOne/Developer/Dev.storyboard
AudioKitSynthOne/Developer/DevViewController.swift
AudioKitSynthOne/Developer/Manager+DevView.swift
AudioKitSynthOne/Developer/README.md
AudioKitSynthOne/Presets/PresetDataManager.swift
AudioKitSynthOne/Settings/AppSettings.swift

Added freezing for arp+sequencer in the DEV panel.
This PR will:
When loading a preset ignore the preset's arp+sequencer parameters if the freeze arp+sequencer app setting is true.
When saving a preset: will capture the current dsp parameters regardless of "freezing" status so that what you hear is what you save.
Clarify this behavior in the documentation.

"What You Hear Is What You Save". WYHIWYS

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp

Previously Delay Changes coming in from the model would not be smoothed
when updated in the process block, thus resulting in loud clicks.
This would occur not only when changing the delay itself, but also in case of tempo-sync (and with tempo changes propagated through MIDI Sync or Link).
Smoothing the delay time gives it a more analogue feel on changes and gets rid of the
click. (Implementing a fade on changes might require more work, potentially touching the Soundpipe Lib itself) 
I'm not sure if this was a conscious decision or an oversight, happy to close this if it was on purpose.

Smooth Delay Changes

---

AudioKitSynthOne/Controls/Buttons/SynthButton.swift
AudioKitSynthOne/Controls/Buttons/ToggleButton.swift
AudioKitSynthOne/Controls/Buttons/ToggleSwitch.swift
AudioKitSynthOne/Controls/Knobs/Knob.swift
AudioKitSynthOne/Controls/Stepper/Stepper.swift
AudioKitSynthOne/DSP/Conductor.swift
AudioKitSynthOne/Effects/UI Components/LFOToggle.swift
AudioKitSynthOne/Effects/UI Components/LFOWavePicker.swift
AudioKitSynthOne/Generators/UI Components/FilterTypeButton.swift
AudioKitSynthOne/Generators/UI Components/MorphSelector.swift
AudioKitSynthOne/Presets/PresetDataManager.swift
AudioKitSynthOne/Sequencer/UI Components/ArpButton.swift
AudioKitSynthOne/Sequencer/UI Components/ArpDirectionButton.swift
AudioKitSynthOne/Sequencer/UI Components/SliderTransposeButton.swift
AudioKitSynthOne/Sequencer/UI Components/VerticalSlider.swift
AudioKitSynthOne/TouchPad/UI Components/AKVerticalPad.swift
README.md

Double tapping a knob will restore the default value as specified by the last loaded preset.
Each UI Element has a defaultCallback closure which will set the component to the default value when called.
A temporary copy of the synth parameters is made once a new preset has been loaded or the current one been saved.
ping @analogcode - git history is chronological, so review commit-by-commit should be possible.

Double Tap to Default

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel.mm

We're allocating new memory for notestates in restoreValues.
This gets called twice, when the engine initializes and
when old DSP Parameters get restored resulting in double allocation.
We only need to allocate once, and that's in init.

Fix: Memory Leaks from prev. commit

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel+destroy.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+didChanges.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+process.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+reset.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+setup.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+toggleKeys.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.mm

Removing the use of malloc/free in favour of
automatic memory management via unique_ptr.
Even if the kernel gets initialized twice, unique_ptr
will delete the old instances.

Remove malloc usage of NoteStates

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel+destroy.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.mm

The Portamento compute port should always be allocated,
no matter if a voice has portamento or not.
This is being handled later in the process section, where based on
a preset portamento is being computed or not.

Fix Portamento Memory Leak

---

AudioKitSynthOne/DSP/Audio Unit/S1AudioUnit.mm

As discussed on Slack:
Move kernel and context teardown from the render allocation
block to the deallocation block.
Tested this against the iPad Air 2 that would previously crash.
ping @analogcode @marcussatellite

Move teardown ops to deallocation

---

AudioKitSynthOne/Presets/PresetsViewController/Presets+CategoryDelegate.swift
AudioKitSynthOne/Presets/PresetsViewController/Presets+LoadSaveManipulate.swift
AudioKitSynthOne/Presets/PresetsViewController/Presets+UITableViewDelegate.swift
AudioKitSynthOne/Presets/PresetsViewController/PresetsViewController.swift

This should be called manually when e.g. the category changes or
presets have been loaded.
Measurement of `func loadBanks()`
Before:
`Presets+LoadSaveManipulate.swift:loadBanks():34:Initializing presets: COMPLETE IN SEC:  3.9090490341186523 seconds`
After
`Presets+LoadSaveManipulate.swift:loadBanks():34:Initializing presets: COMPLETE IN SEC: 0.38115596771240234`
Resulting in a ~3.5s faster load times (in Debug)

Move Select Current Preset Outside of Setter

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel+process.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp

Introduce an enum for Arpegiator modes to make
the different arp-modes a bit more readable in code.

Introduce ArpMode Enum

---

AudioKitSynthOne.xcodeproj/project.pbxproj
AudioKitSynthOne/Audiobus/Manager+Audiobus.swift
AudioKitSynthOne/DSP/AKSynthOne.swift
AudioKitSynthOne/DSP/Audio Unit/S1AudioUnit.mm
AudioKitSynthOne/DSP/Kernel/S1DSPCompressor.hpp
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+destroy.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+process.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.mm
AudioKitSynthOne/MIDI/MIDISettingsViewController.swift
AudioKitSynthOne/MIDI/Manager+MIDIListener.swift
AudioKitSynthOne/Manager/Manager.swift
Podfile

Hey everyone,
I took a stab at making the Kernel more RAII friendly.
I also extracted the C-Calls to the Compressor into a separate class to handle all RAII (and also inject the DSPParameters at Compile-Time).
Please take a look at 
https://github.com/AudioKit/AudioKitSynthOne/commit/b29f6690f174922d7d9194e63a01cce4675a30e1 specifically.
This PR is also dependent on https://github.com/AudioKit/AudioKit/pull/1704 in the AK Repo.
I didn't notice any increase in CPU Performance with this.
ping @aure @marcussatellite @analogcode

Use RAII in C++ in DSP Kernel

---

AudioKitSynthOne.xcodeproj/project.pbxproj

Add -fno-aligned-allocation since C++17 in 10.2
enforces aligned allication which iOS <11 does not support.
ping @analogcode

Add -fno-aligned-allocation to Compile Flags

---

AudioKitSynthOne/MIDI/Manager+MIDIListener.swift

We have gotten a few reports where third parties are
implementing MIDI wrong, using Velocity of 0 for
Note Off.
Therefore this commit checks for velocity and re-routes
the incoming MIDI message to the Note Off handler.
Examples:
- Using Synth One in AUM through the IAA Port.
- Using Synth One with IK Multimedia iRig Keys I/O 49*
*See another Screenshot [1] here: http://i.imgur.com/Sui8JxF.png
[1] https://cgi.ikmultimedia.com/ikforum/viewtopic.php?f=12&t=12920 
Add to Release Notes:
- Improved playing external MIDI from devices that deviate from the MIDI standard.

Treat Velocity 0 as Note Off

---

AudioKitSynthOne.xcodeproj/project.pbxproj
AudioKitSynthOne/Base.lproj/Main.storyboard
AudioKitSynthOne/Keyboard/KeyboardSettingsViewController.swift
AudioKitSynthOne/MIDI/MIDISettingsViewController.swift
AudioKitSynthOne/MIDI/Manager+MIDISettingsPopOverDelegate.swift
AudioKitSynthOne/Navigation/Manager+Navigation.swift
AudioKitSynthOne/Settings/AppSettings.swift
AudioKitSynthOne/Tunings/Model/TuningBank.swift
AudioKitSynthOne/Tunings/Model/Tunings.swift
AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanel+TuneUpDelegate.swift
AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanel+UITableViewDataSource.swift
AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanel+UITableViewDelegate.swift
AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanelController.swift

This PR makes S1 always launches with 12ET, unless the user opts into "launch with last tuning", which is a new setting on the settings popover.

Tuning bank on launch

---

AudioKitSynthOne/AppDelegate.swift
AudioKitSynthOne/Private.swift
Podfile

This PR adds support to automatically and anonymously collect Crash Log and basic statistics to MS App Center.
In the long-run this will help us identify crashes that we are unable to reproduce locally and therefore improve the stability of Synth One.
API Keys are removed from public repo as with other services we use.
I'll hand over instructions to @analogcode as he currently needs to upload the symbols to MS App Center for us to see where crashes are happening.

Add Support for Crash Log Collection

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel+toggleKeys.mm

Remove additional playingNotesDidChange calls from turnon/offkey.
I believe this would occasionally cause stuck notes in the UI due
to potential double notifications within one render-loop.
(and may be a source for crashing the AEMessageQueue)
@aure I added you to this because I saw you added it back then. Not sure if there was any particular reason for these additional notifications, at least in my tests it didnt make a difference.
**Release Note**
- Fixed a bug that would occasionally cause notes to be displayed as playing in the UI when they are not.

Remove additional playingNotesDidChange calls

---

AudioKitSynthOne/DSP/Sequencer/S1Sequencer.mm

**Release Note**: Bug fixes and performance improvements 😄 (honestly, I wouldn't put this in the notes, it would improve performance a bit, but i doubt its significantly)
-----
AEArray is technically still an Objective C object, by not
using the __weak prefix we were increasing/decreasing the ref
count each time we passed this object in.

Fix reference count for Held Notes

---

AudioKitSynthOne/Presets/PresetsViewController/Presets+LoadSaveManipulate.swift

**Release Note**: Fixed a bug that could lead to a crash when selecting Presets through MIDI CC.
-----
In this report that came in through MS AppCenter presets
can be selected via MIDI CC. Unfortunately also banks
with zero presets can get chosen which is where the modulo
zero operation is triggered that ultimately leads to a crash.;
Can't think of a good solution to this right now, so I'm patching
this up with an early return.
@marcussatellite @analogcode this is one from our MS App Center crashes.
@aure I think this one might be in D1 as well.

Do not select empty preset banks

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp

We are having a retain cycle here. AudioUnit retains the DSPKernel,
and the DSPKernel retains the Audiounit. Thus these will never properly deallocate.
@aure @marcussatellite : while trying to get to the root of the AEMessageQueue issues, I found this little issue. It probably doesnt change much for the user because S1AudioUnit and the DSPKernel are almost always alive.

Keep weak reference to S1AudioUnit

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.mm

Setup the parameter tree and defaults when we instantiate
the kernel instead of calling init.
Init is called a second time in `allocateRenderResourcesAndReturnError` in `S1AudioUnit.m`
without destroying the SoundPipe objects therefore resulting in a memory leak.
According to Apple's documentation `allocateRenderResourcesAndReturnError` is the place where we are supposed to allocate all the DSP stuff.
Fixes top of instantiation memory leaks:
ping @aure @analogcode @marcussatellite

Setup Parameter Tree in DSPKernel constructor

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel+destroy.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.mm

Fix a crash that will occur when headphones are unplugged
on certain iOS Devices.
This was introduced earlier when trying to fix memory leaks,
unfortunately we are running into a double-free situation with
the C objects now.
We're now instead tracking state of the kernel initialization
in order to avoid those memory leaks.
ping @aure @marcussatellite @analogcode 
Seems like I wasn't careful enough in https://github.com/AudioKit/AudioKitSynthOne/pull/84

Fix Crash on deallocation of render resources

---

AudioKitSynthOne/Manager/Manager.swift

Fix the logic bug introduced in https://github.com/AudioKit/AudioKitSynthOne/commit/10bb67f91f547df22c0cf7bd74732a7da90dd98e to restore polyphonic mode.
ping @marcussatellite @analogcode  - maybe give this a test run :)

Fix: Restore Polyphonic mode

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp

Fix slow transpose/pitchbend smoothing by disabling it in the AUParameters.
Tested both with UI and ext. MIDI.

Fix pitchbend smoothing

---

AudioKitSynthOne.xcodeproj/project.pbxproj
AudioKitSynthOne/DSP/Note State/S1NoteState.mm

**Release Notes:** Sequencer is now retriggering notes of the same key in poly mode as expected.
-------
When we are doing note stealing and using this helper
we should also reinitialize the ADSR curves or else we would
be in release land forever.
@analogcode @marcussatellite

Fix: Add missing ADSR initialization

---

AudioKitSynthOne.xcodeproj/project.pbxproj
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+destroy.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+process.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp
AudioKitSynthOne/DSP/Kernel/S1DSPKernel.mm
AudioKitSynthOne/DSP/Kernel/S1DSPMoogLadder.hpp
AudioKitSynthOne/DSP/Note State/S1NoteState.hpp
AudioKitSynthOne/DSP/Note State/S1NoteState.mm

Posting this as an RFC.
------
All profiling was done under the same circumstances.
AudioKit SDK through CocoaPods is compiled with `-0s (Fastest, Smallest)` even for Debug builds, so in order to replicate, same had to be done with SynthOne.
For playback, I used a 3-Note held Chord with the sequencer activated to increase polyphony.
SoundPipe Moog Ladder: ~36-43%
S1DSPMoogLadder: ~27-35%
***SoundPipe***
***S1DSPMoogLadder***
The sound is pretty much he same, because of identical sources for the algorithms.
In both modules `tanh` calculation is the most expensive operation, and it seems like the one in @PaulBatchelor s implementation is actually the cheapest available. Alternatives like `vox_fasttanh` (as discussed [here](https://www.kvraudio.com/forum/viewtopic.php?t=388650&postdays=0&post …

RFC: Replace Soundpipe Moog Ladder with S1DSP Version

---

AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanelController.swift

Override the global appearance for the Bank back button.

Fix Banks Button tintColor

---

AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanelController.swift

Introduce a dirty workaround for the barbuttonitem appearance.
This will ensure the appearance changes only to the local scope.
Needs proper fix.

Introduce workaround for BarButtonItem Appearance

---

AudioKitSynthOne/Info.plist

Add description required by iOS 13 to tell users why
we want access to Bluetooth.

Add NSBluetoothAlwaysUsageDescription

---

AudioKitSynthOne.xcodeproj/project.pbxproj
AudioKitSynthOne/AppDelegate.swift
AudioKitSynthOne/Audiobus/Conductor+Audiobus.swift
AudioKitSynthOne/Audiobus/Manager+Audiobus.swift
AudioKitSynthOne/DSP/Conductor.swift
AudioKitSynthOne/Generators/GeneratorsPanelController.swift
AudioKitSynthOne/Keyboard/Manager+Keyboard.swift
AudioKitSynthOne/MIDI/Manager+MIDIListener.swift
AudioKitSynthOne/MIDI/Manager+MIDISettingsPopOverDelegate.swift
AudioKitSynthOne/Manager/Manager.swift
AudioKitSynthOne/Settings/Manager+AppSettings.swift

Hey,
Please read each commit in the history to see whats going on.
TL'DR:
- Moved a lot of audio-engine functionality that was called from the View Code into the Conductor.
- Instantiation of Engine and Conductor is now happening in AppDelegate so it's guaranteed to only be called once
- AudioPlot is also a part of the Conductor now, better solutions are appreciated because it's technically UI Code (with an Engine dependency)
- Reinstantiated the Constraints from @analogcode  previous experiments
- AudioBus MIDI Code is now part of the Conductor and the Manager is a delegate to incoming AB Midi messages.
Please test this if possible, especially the AudioBus related stuff.

iOS 13 Crash Fixes

---

AudioKitSynthOne.xcodeproj/project.pbxproj
AudioKitSynthOne/About/Mailing List/MD5Helpers.swift
AudioKitSynthOne/About/Mailing List/MailchimpService.swift
AudioKitSynthOne/About/Mailing List/MailingListViewController.swift
Podfile

Hey everyone,
this PR removed the dependency on the ChimpKit SDK.
**Background**: The ChimpKit SDK repo has not been updated in 5-6 years and is showing it's age. It does not compile when using Catalyst (Catalina) as a target and it is using the deprecated APIv2 of MailChimp.
This API is well documented and I've written a little class against it.
**Changes**: ChimpKit is removed from PodFile. A new class called `MailChimp` is being put in place as a drop-in replacement with a similar API as before. Higher-level changes are therefore minimal.
**New**: Previously users had no choice to resubscribe when they unsubscribed in the past. This PR adds functionality and checks that - if a user had subscribed in the past, we will send him/her an "opt-in" email. The reason is that we might want to …

Replace ChimpKit SDK Dependency

---

AudioKitSynthOne.xcodeproj/project.pbxproj
AudioKitSynthOne/AppDelegate+PlatformServices.swift
AudioKitSynthOne/AppDelegate.swift
AudioKitSynthOne/Manager/Manager+PushNotification.swift

Refactor the way we talk to OneSignal and MSAppCenter.
Since none of these are currently available we are moving those into a Platform-dependent service file that's being called at launch.
This way we keep the AppDelegate clean from Platform-dependent code.
Based on https://github.com/AudioKit/AudioKitSynthOne/pull/120 (Please merge that one first)

[Cataylst] Refactor Platform Services/Dependencies

---

AudioKitSynthOne.xcodeproj/project.pbxproj
AudioKitSynthOne/Generators/Base.lproj/Generators.storyboard
AudioKitSynthOne/Generators/GeneratorsPanelController.swift
AudioKitSynthOne/MIDI/MIDIRecordButton.swift

Here's an alternative take on https://github.com/AudioKit/AudioKitSynthOne/pull/124 with a little less code and reusing the `MIDIToggleButton`.
**Dev Changes**
We're using a new class called MIDIRecordButton that inherits from MIDIToggleButton.
Instead of using PaintCode we add a Circle Subview and when `isOn` is true, we animate
the backgroundColor of said Circle View.
**User Facing Changes**
The UI is now more in line with the rest of Synth One. An active recording is indicated by both the time progressed as well as the animated button.
@marcussatellite @analogcode adding the SubView in `layoutSubviews` is probably not the right place, let me know if you know of a better function for this.

Add recording button

---

AudioKitSynthOne/MIDI/MIDIRecordButton.swift

**Dev Changes**
In `ToggleButton.swift` we define callbacks on both `touchesBegan` and `touchesEnded`.
Under certain conditions this results in two callbacks being fired rapidly after each other, one at the beginning and one at the end.
@marcussatellite I see you added this class, do you mind taking a look as to why we did this in the first place?
We should probably remove touchesEnded at some point, but I want to avoid introducing potentially breaking changes before rolling this out.
**User Changes**
Record button now behaves as expected and does not cause occasional immediate subsequent recordings anymore.

Fix MIDIRecordButton double Callbacks

---

AudioKitSynthOne/Audiobus/Audiobus.swift

Introduced this in a64d636b6cd17f23bfafe02456ae5b94ead15141 accidentally
while committing a bunch of Catalina prep work to the repo.
Should've looked more closely.

Fix IAA Bug from Catalina Work

---

AudioKitSynthOne/About/AboutViewController.swift
AudioKitSynthOne/Controls/Buttons/SynthButton.swift
AudioKitSynthOne/MIDI/MIDISettingsViewController.swift
AudioKitSynthOne/Manager/Manager.swift
AudioKitSynthOne/Presets/BankEditorViewController.swift
AudioKitSynthOne/Presets/PresetEditorViewController.swift
AudioKitSynthOne/Presets/PresetsViewController/Presets+BankPopOverDelegate.swift
AudioKitSynthOne/Presets/PresetsViewController/Presets+CategoryDelegate.swift
AudioKitSynthOne/Presets/PresetsViewController/Presets+LoadSaveManipulate.swift
AudioKitSynthOne/Presets/PresetsViewController/Presets+PresetCellDelegate.swift
AudioKitSynthOne/Presets/PresetsViewController/Presets+SearchDelegate.swift
AudioKitSynthOne/Presets/PresetsViewController/Presets+UIDocumentPickerDelegate.swift
AudioKitSynthOne/Presets/PresetsViewController/PresetsViewController.swift
AudioKitSynthOne/TouchPad/TouchPadPanelController.swift
AudioKitSynthOne/Tunings/TuningsPanelController/TuningsPanelController.swift

BUGFIX: Preset reorder bug, reported by Francis Preve
Impacts all instances of "SynthButton"
Tested:
PASSED
AboutViewController.swift
@IBOutlet weak var videoButton: SynthButton! // should always be true
@IBOutlet weak var reviewButton: SynthButton!
@IBOutlet weak var githubButton: SynthButton!
@IBOutlet weak var webButton: SynthButton!
PASSED
MIDISettingsViewController.swift
@IBOutlet weak var resetButton: SynthButton!
PASSED
Manager.swift
@IBOutlet weak var midiButton: SynthButton!
@IBOutlet weak var keyboardToggle: SynthButton!
@IBOutlet weak var configKeyboardButton: SynthButton!
@IBOutlet weak var modWheelSettings: SynthButton!
@IBOutlet weak var midiLearnToggle: SynthButton!
PASSED
BankEditorViewController.swift
@IBOutlet weak var cancelButton: SynthButton!
@IBOutlet weak var …

BUGFIX: Reorder bug reported by Francis Preve

---

AudioKitSynthOne/DSP/Audio Unit/S1AudioUnit.h
AudioKitSynthOne/DSP/Audio Unit/S1AudioUnit.mm
AudioKitSynthOne/DSP/Kernel/S1DSPKernel+didChanges.mm

Many crashes are in the message queue after it’s been dispatched…very difficult to debug.
Create a dsp/main thread message queue for each type of event:
AEMessageQueue* _messageQueueDependentParameter;
AEMessageQueue* _messageQueueBeatCounter;
AEMessageQueue* _messageQueuePlayingNotes;
AEMessageQueue* _messageQueueHeldNotes;

Split dsp message queues

---

AudioKitSynthOne.xcodeproj/project.pbxproj
AudioKitSynthOne/DSP/Audio Unit/S1AudioUnit.h
AudioKitSynthOne/DSP/Audio Unit/S1AudioUnit.mm
AudioKitSynthOne/DSP/Audio Unit/S1MessageQueues.h
AudioKitSynthOne/DSP/Audio Unit/S1MessageQueues.mm

Subclass message queues for crash reports, which report class names in stack traces.
i.e., 
@interface AEMessageQueueDependentParameter: AEMessageQueue
@end
@interface AEMessageQueueBeatCounter: AEMessageQueue
@end
@interface AEMessageQueuePlayingNotes: AEMessageQueue
@end
@interface AEMessageQueueHeldNotes: AEMessageQueue
@end

Subclass message queues for crash reports

---

AudioKitSynthOne/DSP/Kernel/S1DSPKernel.hpp

Fix reverb wet compressor makeup gain parameter name in S1DSPKernel. Closes #168

Fix parameter name
